<?php
include 'header.php'; // INCLUDING HEADER
?>

<div class="container-fluid main_page_heading">
    <div class="jumbotron bvnt_bg_col">
        <div class="row">
            <div class="jumbo_page_heading text-center">
                <h2>Terms & Conditions</h2>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-sm-10 col-md-offset-1">
            <h3>1. ABOUT US</h3>
            <h4>1.1 Boovent</h4>
            <p>Boovent provides an online event ticketing and registration platform. Through this platform people can create, search, share and book the events.</p>
            
            <h4>1.2 Services</h4>
            <p>The website and the domain <a href="www.boovent.com">www.boovent.com</a> and all the webpages and services on the site are offered and provided by Boovent. We refer to all these as “Services.” </p>
            
            <h4>1.3 Users</h4>
            <p>Boovent provides a very simple and easy platform for the organizers, promoters, institutions and event managers (“ORGANIZERS”) to create their own event page, their own profile, and company profile and also to promote the event pages to the visitors (“ATTENDEES”) on the platform who intend to buy the events passes or register for the event. We refer to all the organizers, attendees and visitors on the website collectively as “Users” OR “You.”</p>

            <h3>2. TERMS OF SERVICES</h3>
            <h4>2.1 Terms of use</h4>
            <p>The terms of use sets forth the terms and conditions under which you will use any services on the platform. By accepting these terms you accept to use these terms without any changes. If you do not agree by an f the terms mentioned here, you cannot use any services on this platform. By accepting the terms you make a binding contract with Boovent. Nothing in these terms can be modified by any other person.</p>

            <h3>3. USE OF SERVICES</h3>
            <h4>3.1 Website</h4>
            <p>Boovent allows you a personal, non-transferable and limited right to access, search, browse, buy and register for any events or services offered by the platform, and if you are an organizer Boovent allows you to post your event, make event page, organizer profile, company profile, track your events, collect sale and promote events to the users in the website. All these services can be held after the agreement of the Terms of Use (Section 2.1). The events posted shall be permitted under the local town, city, state or any specific region. Users have to make sure that no posts of their events can in any way copy, modify, dissemble, translate and reverse engineer any part of the service offered by Boovent. Once the organizer is done with the posting of the event, he cannot modify the particular event. The event will just be under moderation and after getting proper confirmations about the event, the event will be made active.</p>

            <h3>4. BOOVENT’S ROLE</h3>
            <h4>4.1 Mediator</h4>
            <p>Boovent is not the Organizer or owner of any events that are on the platform. Boovent provides a platform for different organizers to post their events and make the sell. Boovent acts like a middle man. Boovent helps organizers to track the number of event tickets sold and even track the revenue generated by the organizer. It is the responsibility of any organizer to post the events which are in agreement to the terms of use of Boovent and even with the permission of any locality where the event is taking place.</p>
            <h4>4.2 Payment</h4>
            <p>Boovent provides different options for customers to make payment for the events and even different payout methods for organizers to collect the payment.</p>
            <h4>4.3 Fees</h4>
            <p>Browsing the events on the platform, creating and posting of events is free. Boovent charges when you make a sell or buy a paid ticket. The basic pricing will be same for all the events, but the final outcome pricing may vary from organizer to organizer depending on the binding made between Boovent and the organizer. Organizer has an option to bear the complete Boovent charge or pass it on to customers who will buy the tickets or he can choose to divide the Boovent charge equally. Boovent does not control the fees that is charged by your bank or credit/debit card companies while buying the tickets. Boovent charges its share of the paid events, the charges are mentioned <a href="#">here</a>.</p>
            <h4>4.4 Refund</h4>
            <p>All the transactions that are going to be held are between organizers and attendees, so in any circumstances of refund, Boovent can only initiate the refund process once Boovent gets the confirmation from the organizer. In case if the event is cancelled, attendees can contact <a href="#">here</a> and ask for a refund. The refund will only be initiated after confirmation from the organizer. Boovent will not be responsible if there is a denial of refund from the organizer.</p>

            <h3>5. ACCOUNT AND SECURITY</h3>
            <h4>5.1 Registration</h4>
            <p>Under the user registration you will provide certain information. You agree that all the information filled by you is true. If you are using the platform as a personal account or as a company account, the information provided by you should be accurate and complete. You agree to keep the information in your account updated and modify the changes from time to time, accordingly. If any dispute is observed by any user (organizer/attendee), Boovent holds the power to terminate or suspend the account of the same anytime it is required to resolve the dispute.</p>
            <h4>5.2 Password and Privacy</h4>
            <p>You are solely responsible to keep the password of your account undisclosed and also responsible for all the activities that take place under the name of your account. You can notify Boovent here as soon as you find any unusual activity with your account.</p>
            <p>5.3 Age Limitation</p>
            <p>Boovent provides a platform for kid’s activities. The age limitation to use any service on the platform is minimum eighteen (18) years of age. Users with the age below eighteen years can also access the service under the guidance of some guardian.</p>

            <h3>6. EVENT ORGANIZER’S TERMS OF USE</h3>
            <h4>6.1 Posting of event</h4>
            <p>For any organizer to post any event he should fill the basic information asked by Boovent. After providing the basic information organizer can have an access to the services provided by the platform. Once the event details are filled by the organizer and he posts the event, the event will go under moderation and a cross check of the event will be done by the Boovent team. As soon as the moderation is done, the event will be live. While posting events, organizer need to specify the special terms that are required for the particular event.</p>
            <h4>6.2 Payout options</h4>
            <p>As soon as the event is live the organizer will be asked to fill in the payout details. He will be asked to fill the details in certain period of time. If the organizer fails to provide the payout details, Boovent holds the right to withhold any amount that the event has made by selling the tickets as long as the details are not provided. Organizer agrees that the payout details provided by the organizer will be used by Boovent for payout method and if that requires the information to be shared by the payment processing partners the organizer have no issues with it. In a case if the event is posted that contains some sensitive data, pornography, prostitution, Boovent holds the right to terminate the account or the event.</p>
            <h4>6.3 Order confirmation by Boovent</h4>
            <p>Once Boovent receives the order from the attendee, it will provide a specific code for a specific booking. Boovent will then notify the organizer of the booking and ask the organizer to make the reservation on the particular code.</p>
            <h4>6.4 Changes in published event</h4>
            <p>The organizer cannot make any changes in the event once it is published from his side. Organizer needs to post another event and remove the previous event’s data if any change is to be done. For any minor change for an event, the organizer need to contact Boovent <a href="#">here</a>.</p>

            <h3>7. CERTAIN RESTRICTIONS</h3>
            <p>You agree that you are not supposed to use the services on the platform</p>
            <ol>
                <li>By posting anything that is against the law, unethical, harms the religion in any ways, threatening, abusive, targets audience on basis of language.</li>
                <li>Harm minors in any ways.</li>
                <li>By posting anything that affects the privacy of any celebrity or publicity, affects the patent or trademark of any institutions.</li>
                <li>Advertise your event and sell the tickets independently.</li>
                <li>Resale tickets.</li>
                <li>Stalk or harass any person.</li>
            </ol>
            <h3>8. REFUND</h3>
            <p>All the transactions that are going to be held are between organizers and attendees, so in any circumstances of refund, Boovent can only initiate the refund process once Boovent gets the confirmation from the organizer. In case if the event is cancelled, attendees can contact <a href="contact.php">here</a> and ask for a refund. The refund will only be initiated after confirmation from the organizer. Boovent will not be responsible if there is a denial of refund from the organizer.</p>
            <h3>9. Opt-out/Cancellation Guideline</h3>
            <p>As customer denies or cancel ticket after purchasing then it is solely dependent upon organizer's guideline provided to us during event creation. If still problem persist <a href="contact.php">contact us</a>.</p>
        </div>
    </div>
</div>

<!-- <br><br> -->
<?php
include 'footer.php'; // INCLUDING FOOTER
?>